// Permission constants
export const PERMISSIONS = {
  // Supplier permissions
  VIEW_SUPPLIER: 'VIEW_SUPPLIER',
  CREATE_SUPPLIER: 'CREATE_SUPPLIER',
  UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
  DELETE_SUPPLIER: 'DELETE_SUPPLIER',

  // Product permissions
  VIEW_PRODUCT: 'VIEW_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',

  // Order permissions
  VIEW_ORDER: 'VIEW_ORDER',
  CREATE_ORDER: 'CREATE_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  VALIDATE_ORDER: 'VALIDATE_ORDER',
  RECEIVE_ORDER: 'RECEIVE_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',

  // Stock permissions
  VIEW_STOCK: 'VIEW_STOCK',
  VIEW_STOCK_MOVEMENTS: 'VIEW_STOCK_MOVEMENTS',

  // Output Slip permissions
  VIEW_OUTPUT_SLIP: 'VIEW_OUTPUT_SLIP',
  CREATE_OUTPUT_SLIP: 'CREATE_OUTPUT_SLIP',
  VALIDATE_OUTPUT_SLIP: 'VALIDATE_OUTPUT_SLIP',
  CANCEL_OUTPUT_SLIP: 'CANCEL_OUTPUT_SLIP',

  // User management permissions
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS'
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export interface UserPermissions {
  permissions: string[];
}




